project_name: hoodieaf

builds:
  - dir: cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/chayev/hoodieaf/cmd.version={{ .Version }} -extldflags "-static"

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
    replacements:
      darwin: macos

nfpms:
  - file_name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    maintainer: "Michael Ibragimchayev"
    description: "Utility to you know if you need a hoodie or not."
    license: MIT
    formats:
      - deb
    bindir: /usr/bin

brews:
  - tap:
      owner: chayev
      name: homebrew-tap
    commit_author:
      name: "Michael Ibragimchayev"
      email: "michael@chayev.com"
    folder: Formula
    homepage: "https://github.com/chayev/hoodieaf"
    description: "Utility to you know if you need a hoodie or not."
    test: |
      system "#{bin}/hoodieaf", "help"
